#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleWidget.Resource", IsApplication=true)]

namespace SimpleWidget
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int star_logo = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int widget_bg = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int widget_bg_normal = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int widget_bg_pressed = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int widget_bg_selected = 2130771973;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int blog_title = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int bullet = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int creator = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int message = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int widget = 2130837509;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int widget_message = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int widget_word = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int widget_loading = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int widget_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int BulletPoint = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Text = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int Text_BlogTitle = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int Text_Creator = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int Text_Loading = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int Text_WordType = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int WidgetBackground = 2131034118;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F060000
			public const int widget_word = 2131099648;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
